theme: jekyll-theme-minimal
title: Swati
description: [Researcher<br/>
Artificial Intelligence Laboratory<br/>Jožef Stefan Institute<br/>Ljubljana, Slovenia]
show_downloads: false
logo: /assets/img/pic.jpeg
